<?php 
	/**
	 * KalturaSupport base configuration
	 * 
	* Do not edit this file instead use LocalSettings.php and
	* $wgMwEmbedModuleConfig[ {configuration name} ] = value; format
	*/
	global $wgKalturaUseManifestUrls;
	
	return array (
		'Kaltura.ServiceUrl' => 'http://www.kaltura.com',
		'Kaltura.StatsServiceUrl' => 'http://www.kaltura.com',
		'Kaltura.ServiceBase' => '/api_v3/index.php?service=',
		'Kaltura.CdnUrl' => 'http://cdnakmi.kaltura.com',
		// By default tell the client to cache results
		'Kaltura.NoApiCache' => false, 

		// By default support apple adaptive
		//'Kaltura.UseAppleAdaptive' => true,
		
		// if Manifest urls should be used: 
		'Kaltura.UseManifestUrls' => $wgKalturaUseManifestUrls,
		
		// By default we should include flavorIds urls for supporting akami HD
		'Kaltura.UseFlavorIdsUrls' => true,
		
		// A video file for when no suitable flavor can be found
		'Kaltura.MissingFlavorSources' => array(
			array(
				'src' => 'http://www.kaltura.com/p/243342/sp/24334200/playManifest/entryId/1_g18we0u3/flavorId/1_ktavj42z/format/url/protocol/http/a.mp4',
				'type' => 'video/h264'
			),
			array(
				'src' => 'http://www.kaltura.com/p/243342/sp/24334200/playManifest/entryId/1_g18we0u3/flavorId/1_gtm9gzz2/format/url/protocol/http/a.ogg',
				'type' => 'video/ogg'
			),
			array(
				'src' => 'http://www.kaltura.com/p/243342/sp/24334200/playManifest/entryId/1_g18we0u3/flavorId/1_bqsosjph/format/url/protocol/http/a.webm',
				'type' => 'video/webm'
			)
		),
		// Black video sources. Useful for capturing play user gesture events on a live video tag for iPad
		// while displaying an error message or image overlay and not any 'real' video content.
		'Kaltura.BlackVideoSources' => array(
			array(
				'src' => 'http://www.kaltura.com/p/243342/sp/24334200/playManifest/entryId/1_vp5cng42/flavorId/1_6wf0o9n7/format/url/protocol/http/a.mp4',
				'type' => 'video/h264'
			),
			array(
				'src' => 'http://www.kaltura.com/p/243342/sp/24334200/playManifest/entryId/1_vp5cng42/flavorId/1_oiyfyphl/format/url/protocol/http/a.webm',
				'type' => 'video/webm'
			),
			array(
				'src' => 'http://www.kaltura.com/p/243342/sp/24334200/playManifest/entryId/1_vp5cng42/flavorId/1_6yqa4nmd/format/url/protocol/http/a.ogg',
				'type' => 'video/ogg'
			)
		),
		// Do not send KS for isLive requests
		'SkipKSOnIsLiveRequest' => true
	);