<div id="hps-templates"></div>
<div id="playbackModeSelector" style="float:right"></div>
<script>
updatePlaybackModeSelector( $('#playbackModeSelector') );
</script>
<h1>Standard Player Templates</h1>
<div class="entry-content">
	<p class="header">There are more then a dozen player templates pre-configured inside the KMC (in the Studio Tab). Once a template is selected, build out your player with simple point-and-click selections of colors, buttons, player sizes, ad configurations, etc.</p>
<div class="blurb-full">
<h2>Players with Hovering Controllers</h2>
<div class="wpcol-one-half">
<h3>Template: New Player &#8211; Hovering Controllers</h3>
<p><script type="text/javascript" src="http://www.kaltura.com/p/1062871/sp/106287100/embedIframeJs/uiconf_id/10489411/partner_id/1062871"></script><object id="kaltura_player_1352425229" name="kaltura_player_1352425229" type="application/x-shockwave-flash" allowFullScreen="true" allowNetworking="all" allowScriptAccess="always" height="322" width="430" bgcolor="#000000" xmlns:dc="http://purl.org/dc/terms/" xmlns:media="http://search.yahoo.com/searchmonkey/media/" rel="media:video" resource="http://www.kaltura.com/index.php/kwidget/cache_st/1352425229/wid/_1062871/uiconf_id/10489411/entry_id/1_u05a0sn3" data="http://www.kaltura.com/index.php/kwidget/cache_st/1352425229/wid/_1062871/uiconf_id/10489411/entry_id/1_u05a0sn3"><param name="allowFullScreen" value="true" /><param name="allowNetworking" value="all" /><param name="allowScriptAccess" value="always" /><param name="bgcolor" value="#000000" /><param name="flashVars" value="streamerType=hdnetwork&amp;akamaiHD.loadingPolicy=preInitialize&amp;akamaiHD.asyncInit=true&amp;&#038;{FLAVOR}" /><param name="movie" value="http://www.kaltura.com/index.php/kwidget/cache_st/1352425229/wid/_1062871/uiconf_id/10489411/entry_id/1_u05a0sn3" /><a href="http://corp.kaltura.com/products/video-platform-features">Video Platform</a> <a href="http://corp.kaltura.com/Products/Features/Video-Management">Video Management</a> <a href="http://corp.kaltura.com/Video-Solutions">Video Solutions</a> <a href="http://corp.kaltura.com/Products/Features/Video-Player">Video Player</a> <a rel="media:thumbnail" href="http://cdnbakmi.kaltura.com/p/1062871/sp/106287100/thumbnail/entry_id/1_u05a0sn3/width/120/height/90/bgcolor/000000/type/2"></a> <span property="dc:description" content=""></span><span property="media:title" content="Normal web quality video (400kbps)"></span> <span property="media:width" content="451"></span><span property="media:height" content="338"></span> <span property="media:type" content="application/x-shockwave-flash"></span> </object><br />
</div><div class="wpcol-one-half wpcol-last">
<h3>Template: Basic Template &#8211; Hovering Controllers</h3>
<p><script type="text/javascript" src="http://www.kaltura.com/p/1062871/sp/106287100/embedIframeJs/uiconf_id/10489811/partner_id/1062871"></script><object id="kaltura_player_1352426711" name="kaltura_player_1352426711" type="application/x-shockwave-flash" allowFullScreen="true" allowNetworking="all" allowScriptAccess="always" height="322" width="430" bgcolor="#000000" xmlns:dc="http://purl.org/dc/terms/" xmlns:media="http://search.yahoo.com/searchmonkey/media/" rel="media:video" resource="http://www.kaltura.com/index.php/kwidget/cache_st/1352426711/wid/_1062871/uiconf_id/10489811/entry_id/1_u05a0sn3" data="http://www.kaltura.com/index.php/kwidget/cache_st/1352426711/wid/_1062871/uiconf_id/10489811/entry_id/1_u05a0sn3"><param name="allowFullScreen" value="true" /><param name="allowNetworking" value="all" /><param name="allowScriptAccess" value="always" /><param name="bgcolor" value="#000000" /><param name="flashVars" value="streamerType=hdnetwork&amp;akamaiHD.loadingPolicy=preInitialize&amp;akamaiHD.asyncInit=true&amp;&#038;{FLAVOR}" /><param name="movie" value="http://www.kaltura.com/index.php/kwidget/cache_st/1352426711/wid/_1062871/uiconf_id/10489811/entry_id/1_u05a0sn3" /><a href="http://corp.kaltura.com/products/video-platform-features">Video Platform</a> <a href="http://corp.kaltura.com/Products/Features/Video-Management">Video Management</a> <a href="http://corp.kaltura.com/Video-Solutions">Video Solutions</a> <a href="http://corp.kaltura.com/Products/Features/Video-Player">Video Player</a> <a rel="media:thumbnail" href="http://cdnbakmi.kaltura.com/p/1062871/sp/106287100/thumbnail/entry_id/1_u05a0sn3/width/120/height/90/bgcolor/000000/type/2"></a> <span property="dc:description" content=""></span><span property="media:title" content="Normal web quality video (400kbps)"></span> <span property="media:width" content="451"></span><span property="media:height" content="338"></span> <span property="media:type" content="application/x-shockwave-flash"></span> </object><br />
</div><div class="wpcol-divider"></div>
</div>
<div class="blurb-full">
<h2>Players with Vertical Playlists</h2>
<div class="wpcol-one-half">
<h3>Template: New Player &#8211; Vertical Playlist</h3>
<p><script type="text/javascript" src="http://www.kaltura.com/p/1062871/sp/106287100/embedIframeJs/uiconf_id/10489531/partner_id/1062871"></script><object id="kaltura_player" name="kaltura_player" type="application/x-shockwave-flash" allowFullScreen="true" allowNetworking="all" allowScriptAccess="always" height="710" width="400" xmlns:dc="http://purl.org/dc/terms/" xmlns:media="http://search.yahoo.com/searchmonkey/media/" rel="media:video" resource="http://www.kaltura.com/index.php/kwidget/cache_st/1352428502/wid/_1062871/uiconf_id/10489531" data="http://www.kaltura.com/index.php/kwidget/cache_st/1352428502/wid/_1062871/uiconf_id/10489531"><param name="allowFullScreen" value="true" /><param name="allowNetworking" value="all" /><param name="allowScriptAccess" value="always" /><param name="bgcolor" value="#000000" /><param name="flashVars" value="playlistAPI.autoInsert=true&amp;playlistAPI.kpl0Name=Vertical+Playlist+Player+Demo&amp;playlistAPI.kpl0Url=http%253A%252F%252Fwww.kaltura.com%252Findex.php%252Fpartnerservices2%252Fexecuteplaylist%253Fpartner_id%253D1062871%2526subp_id%253D106287100%2526format%253D8%2526playlist_id%253D1_h1ocrzz4" /><param name="movie" value="http://www.kaltura.com/index.php/kwidget/cache_st/1352428502/wid/_1062871/uiconf_id/10489531" /><a href="http://corp.kaltura.com">video platform</a><a href="http://corp.kaltura.com/video_platform/video_management">video management</a><a href="http://corp.kaltura.com/solutions/video_solution">video solutions</a><a href="http://corp.kaltura.com/video_platform/video_publishing">video player</a><span property="dc:description" content=""></span><span property="media:title" content="Kaltura Video"></span><span property="media:width" content="400"></span><span property="media:height" content="710"></span><span property="media:type" content="application/x-shockwave-flash"></span></object><br />
</div><div class="wpcol-one-half wpcol-last">
<h3>Template: Basic Template &#8211; Vertical Playlist</h3>
<p><script type="text/javascript" src="http://www.kaltura.com/p/1062871/sp/106287100/embedIframeJs/uiconf_id/10491141/partner_id/1062871"></script><object id="kaltura_player" name="kaltura_player" type="application/x-shockwave-flash" allowFullScreen="true" allowNetworking="all" allowScriptAccess="always" height="658" width="400" xmlns:dc="http://purl.org/dc/terms/" xmlns:media="http://search.yahoo.com/searchmonkey/media/" rel="media:video" resource="http://www.kaltura.com/index.php/kwidget/cache_st/1352429266/wid/_1062871/uiconf_id/10491141" data="http://www.kaltura.com/index.php/kwidget/cache_st/1352429266/wid/_1062871/uiconf_id/10491141"><param name="allowFullScreen" value="true" /><param name="allowNetworking" value="all" /><param name="allowScriptAccess" value="always" /><param name="bgcolor" value="#000000" /><param name="flashVars" value="playlistAPI.autoInsert=true&amp;playlistAPI.kpl0Name=Vertical+Playlist+Player+Demo&amp;playlistAPI.kpl0Url=http%253A%252F%252Fwww.kaltura.com%252Findex.php%252Fpartnerservices2%252Fexecuteplaylist%253Fpartner_id%253D1062871%2526subp_id%253D106287100%2526format%253D8%2526playlist_id%253D1_h1ocrzz4" /><param name="movie" value="http://www.kaltura.com/index.php/kwidget/cache_st/1352429266/wid/_1062871/uiconf_id/10491141" /><a href="http://corp.kaltura.com">video platform</a><a href="http://corp.kaltura.com/video_platform/video_management">video management</a><a href="http://corp.kaltura.com/solutions/video_solution">video solutions</a><a href="http://corp.kaltura.com/video_platform/video_publishing">video player</a><span property="dc:description" content=""></span><span property="media:title" content="Kaltura Video"></span><span property="media:width" content="400"></span><span property="media:height" content="658"></span><span property="media:type" content="application/x-shockwave-flash"></span></object><br />
</div><div class="wpcol-divider"></div>
</div>
<div class="blurb-full">
<h2>Players with Horizontal Playlists</h2>
<div>
<h3 style="padding:20px 0 0 0;">Template: New Template &#8211; Horizontal Playlist</h3>
<p><script type="text/javascript" src="http://www.kaltura.com/p/1062871/sp/106287100/embedIframeJs/uiconf_id/11187681/partner_id/1062871"></script><object id="kaltura_player_1355182567" name="kaltura_player_1355182567" type="application/x-shockwave-flash" allowFullScreen="true" allowNetworking="all" allowScriptAccess="always" height="330" width="740" bgcolor="#000000" xmlns:dc="http://purl.org/dc/terms/" xmlns:media="http://search.yahoo.com/searchmonkey/media/" rel="media:video" resource="http://www.kaltura.com/index.php/kwidget/cache_st/1355182567/wid/_1062871/uiconf_id/11187681" data="http://www.kaltura.com/index.php/kwidget/cache_st/1355182567/wid/_1062871/uiconf_id/11187681"><param name="allowFullScreen" value="true" /><param name="allowNetworking" value="all" /><param name="allowScriptAccess" value="always" /><param name="bgcolor" value="#000000" /><param name="flashVars" value="streamerType=hdnetwork&amp;akamaiHD.loadingPolicy=preInitialize&amp;akamaiHD.asyncInit=true&amp;playlistAPI.autoInsert=true&#038;playlistAPI.kpl0Name=Vertical Playlist Player Demo&#038;playlistAPI.kpl0Url=http%3A%2F%2Fwww.kaltura.com%2Findex.php%2Fpartnerservices2%2Fexecuteplaylist%3Fuid%3D%26partner_id%3D1062871%26subp_id%3D106287100%26format%3D8%26ks%3D%7Bks%7D%26playlist_id%3D1_h1ocrzz4&#038;{FLAVOR}" /><param name="movie" value="http://www.kaltura.com/index.php/kwidget/cache_st/1355182567/wid/_1062871/uiconf_id/11187681" /><a href="http://corp.kaltura.com/products/video-platform-features">Video Platform</a> <a href="http://corp.kaltura.com/Products/Features/Video-Management">Video Management</a> <a href="http://corp.kaltura.com/Video-Solutions">Video Solutions</a> <a href="http://corp.kaltura.com/Products/Features/Video-Player">Video Player</a>  </object>
</div>
<div>
<h3 style="padding:20px 0 0 0;">Template: Basic Template &#8211; Horizontal Playlist</h3>
<p><script type="text/javascript" src="http://www.kaltura.com/p/1062871/sp/106287100/embedIframeJs/uiconf_id/11187551/partner_id/1062871"></script><object id="kaltura_player_1355181793" name="kaltura_player_1355181793" type="application/x-shockwave-flash" allowFullScreen="true" allowNetworking="all" allowScriptAccess="always" height="330" width="740" bgcolor="#000000" xmlns:dc="http://purl.org/dc/terms/" xmlns:media="http://search.yahoo.com/searchmonkey/media/" rel="media:video" resource="http://www.kaltura.com/index.php/kwidget/cache_st/1355181793/wid/_1062871/uiconf_id/11187551" data="http://www.kaltura.com/index.php/kwidget/cache_st/1355181793/wid/_1062871/uiconf_id/11187551"><param name="allowFullScreen" value="true" /><param name="allowNetworking" value="all" /><param name="allowScriptAccess" value="always" /><param name="bgcolor" value="#000000" /><param name="flashVars" value="streamerType=hdnetwork&amp;akamaiHD.loadingPolicy=preInitialize&amp;akamaiHD.asyncInit=true&amp;playlistAPI.autoInsert=true&#038;playlistAPI.kpl0Name=Vertical Playlist Player Demo&#038;playlistAPI.kpl0Url=http%3A%2F%2Fwww.kaltura.com%2Findex.php%2Fpartnerservices2%2Fexecuteplaylist%3Fuid%3D%26partner_id%3D1062871%26subp_id%3D106287100%26format%3D8%26ks%3D%7Bks%7D%26playlist_id%3D1_h1ocrzz4&#038;{FLAVOR}" /><param name="movie" value="http://www.kaltura.com/index.php/kwidget/cache_st/1355181793/wid/_1062871/uiconf_id/11187551" /><a href="http://corp.kaltura.com/products/video-platform-features">Video Platform</a> <a href="http://corp.kaltura.com/Products/Features/Video-Management">Video Management</a> <a href="http://corp.kaltura.com/Video-Solutions">Video Solutions</a> <a href="http://corp.kaltura.com/Products/Features/Video-Player">Video Player</a>  </object>
</div>
<div class="clear"></div>				
</div> <!-- end .entry-content -->
