<?php

class DataStore {

	private static $instance;

    private function __construct() {}
    private function __clone() {}

    public static function getInstance() {
        if (!DataStore::$instance instanceof self) {
             DataStore::$instance = new self();
        }
        return DataStore::$instance;
    }

	private $baseentryData = array(
		array(
		"mediaType"            => 1,
		"conversionQuality"    => "129452",
		"sourceType"           => "6",
		"searchProviderType"   => null,
		"searchProviderId"     => null,
		"creditUserName"       => null,
		"creditUrl"            => null,
		"mediaDate"            => null,
		"dataUrl"              => "http://cdnbakmi.kaltura.com/p/243342/sp/24334200/flvclipper/entry_id/0_c0r624gh/version/0",
		"flavorParamsIds"      => "0,356431,48572,48592,48582,1,6,5,230931,360461,62581,360451,360471,2,3,4,7",
		"plays"                => 7438,
		"views"                => 18632,
		"lastPlayedAt"         => 1403592866,
		"width"                => 1120,
		"height"               => 480,
		"duration"             => 888,
		"msDuration"           => 888000,
		"durationType"         => null,
		"id"                   => "0_c0r624gh",
		"name"                 => "Sintel Title",
		"description"          => "The film follows a girl named Sintel who is searching for a baby dragon she calls Scales",
		"partnerId"            => 243342,
		"userId"               => "__ADMIN__242942",
		"creatorId"            => "__ADMIN__242942",
		"tags"                 => "",
		"adminTags"            => null,
		"categories"           => "",
		"categoriesIds"        => "",
		"status"               => 2,
		"moderationStatus"     => 6,
		"moderationCount"      => 0,
		"type"                 => 1,
		"createdAt"            => 1314818953,
		"updatedAt"            => 1379703100,
		"rank"                 => 0,
		"totalRank"            => 0,
		"votes"                => 0,
		"groupId"              => null,
		"partnerData"          => null,
		"downloadUrl"          => "http://cdnbakmi.kaltura.com/p/243342/sp/24334200/raw/entry_id/0_c0r624gh/version/0",
		"searchText"           => "_KAL_NET_ _243342_ _MEDIA_TYPE_1|  Sintel Title The film follows a girl named Sintel who is searching for a baby dragon she calls Scales ",
		"licenseType"          => -1,
		"version"              => 0,
		"thumbnailUrl"         => "http://cdnbakmi.kaltura.com/p/243342/sp/24334200/thumbnail/entry_id/0_c0r624gh/version/100004",
		"accessControlId"      => 126432,
		"startDate"            => null,
		"endDate"              => null,
		"referenceId"          => null,
		"replacingEntryId"     => null,
		"replacedEntryId"      => null,
		"replacementStatus"    => 0,
		"partnerSortValue"     => 0,
		"conversionProfileId"  => "129452",
		"redirectEntryId"      => null,
		"rootEntryId"          => "0_c0r624gh",
		"operationAttributes"  => array(),
		"entitledUsersEdit"    => "",
		"entitledUsersPublish" => ""
	));
	private $metadataData = array(
		array(
			'id'                     => 13338971,
			'partnerId'              => 243342,
			'metadataProfileId'      => 3282,
			'metadataProfileVersion' => 22,
			'metadataObjectType'     => 1,
			'objectId'               => '0_c0r624gh',
			'version'                => 721,
			'createdAt'              => 1353273540,
			'updatedAt'              => 1379703100,
			'status'                 => 1,
			'xml'                    => '<metadata>  <AgeConsent>6</AgeConsent>  <Locale>es_419</Locale></metadata>',
		),
		array(
			'id'                     => 16451462,
			'partnerId'              => 243342,
			'metadataProfileId'      => 313142,
			'metadataProfileVersion' => 1,
			'metadataObjectType'     => 1,
			'objectId'               => '0_c0r624gh',
			'version'                => 2,
			'createdAt'              => 1360796034,
			'updatedAt'              => 1360796051,
			'status'                 => 1,
			'xml'                    => '<metadata>  <Permalink>www.kaltura.com</Permalink></metadata>',
		)
	);
	private $sessionData = array(
		"partnerId" => 243342,
		"ks"        => "NjM4NGQwZTg4OWFmOTQ3NzQ4MWQ0YWQwNmJhZDc1YzkyYWE1ZGQwM3wyNDMzNDI7MjQzMzQyOzE0MDM4NTg3NTM7MDsxNDAzNzcyMzUzLjI3MzE7MDt2aWV3Oiosd2lkZ2V0OjE7Ow==",
		"userId"    => 0 
	);
	private $entrycontextdataData = array(
		'isSiteRestricted'      => 'false',
		'isCountryRestricted'   => 'false',
		'isSessionRestricted'   => 'false',
		'isIpAddressRestricted' => 'false',
		'isUserAgentRestricted' => 'false',
		'previewLength'         => '-1',
		'isScheduledNow'        => 'true',
		'isAdmin'               => 'false',
		'streamerType'          => 'hdnetwork',
		'mediaProtocol'         => 'http',
		'storageProfilesXML'    => 'NULL',
		'accessControlMessages' => array(),
		'accessControlActions'  => array(),
		'flavorAssets'          => array(),
		'messages' => array(),
		'actions'  => array()
	);
	private $flavorassetsData = array(
		array(
			'flavorParamsId'             => 5,
			'width'                      => 816,
			'height'                     => 352,
			'bitrate'                    => 391,
			'frameRate'                  => 24,
			'isOriginal'                 => false,
			'isWeb'                      => true,
			'containerFormat'            => 'flash video',
			'videoCodecId'               => 'vp6',
			'status'                     => 2,
			'id'                         => '0_prgxhkso',
			'entryId'                    => '0_c0r624gh',
			'partnerId'                  => 243342,
			'version'                    => '1',
			'size'                       => 51200,
			'tags'                       => 'web,mbr',
			'fileExt'                    => 'flv',
			'createdAt'                  => 1314819002,
			'updatedAt'                  => 1314821131,
			'deletedAt'                  => NULL,
			'description'                => '',
			'URL'						=> 'http://mcott2_tvinci2-s.akamaihd.net/ondemand/201401B/FR_HD_ELLA_THE_ELEPHANT_EP2_PC_SS.ism/Manifest',
			'partnerData'                => '{"type":"flv","url": "http://cdnapi.kaltura.com/p/243342/sp/24334200/playManifest/entryId/0_swup5zao/flavorId/0_prgxhkso/format/url/protocol/http/a.flv"}',
			'partnerDescription'         => NULL,
			'actualSourceAssetParamsIds' => NULL,
		),
		array(
			'flavorParamsId'             => 356431,
			'width'                      => 480,
			'height'                     => 192,
			'bitrate'                    => 400,
			'frameRate'                  => 24,
			'isOriginal'                 => false,
			'isWeb'                      => false,
			'containerFormat'            => '3gp4',
			'videoCodecId'               => 'mpeg-4 visual',
			'status'                     => 2,
			'id'                         => '0_b5cmhwnw',
			'entryId'                    => '0_c0r624gh',
			'partnerId'                  => 243342,
			'version'                    => '2',
			'size'                       => 66867,
			'tags'                       => 'mpeg4,hinted,mobile',
			'fileExt'                    => '3gp',
			'createdAt'                  => 1314819002,
			'updatedAt'                  => 1314819485,
			'deletedAt'                  => NULL,
			'description'                => '',
			'URL'						=> 'http://mcott2_tvinci2-s.akamaihd.net/ondemand/201401B/FR_HD_ELLA_THE_ELEPHANT_EP2_PC_SS.ism/Manifest',
			'partnerData'                => '{"type":"3gp","url": "http://cdnapi.kaltura.com/p/243342/sp/24334200/playManifest/entryId/0_swup5zao/flavorId/0_b5cmhwnw/format/url/protocol/http/a.3gp"}',
			'partnerDescription'         => NULL,
			'actualSourceAssetParamsIds' => NULL,
		),
		array(
			'flavorParamsId'             => 360451,
			'width'                      => 480,
			'height'                     => 192,
			'bitrate'                    => 418,
			'frameRate'                  => 24,
			'isOriginal'                 => false,
			'isWeb'                      => true,
			'containerFormat'            => 'isom',
			'videoCodecId'               => 'avc1',
			'status'                     => 2,
			'id'                         => '1_upx4jp4h',
			'entryId'                    => '0_c0r624gh',
			'partnerId'                  => 243342,
			'version'                    => '1',
			'size'                       => 52531,
			'tags'                       => 'iphone,h264,web,iphonenew   ,mobile,iphonenew',
			'fileExt'                    => 'mp4',
			'createdAt'                  => 1325735073,
			'updatedAt'                  => 1325735700,
			'deletedAt'                  => NULL,
			'description'                => '',
			'URL'						=> 'http://mcott2_tvinci2-s.akamaihd.net/ondemand/201401B/FR_HD_ELLA_THE_ELEPHANT_EP2_PC_SS.ism/Manifest',
			'partnerData'                => '{"type":"h264","url": "http://cdnapi.kaltura.com/p/243342/sp/24334200/playManifest/entryId/0_swup5zao/flavorId/0_cadhics7/format/url/protocol/http/a.mp4"}',
			'partnerDescription'         => NULL,
			'actualSourceAssetParamsIds' => NULL,
		),
		array(
			'flavorParamsId'             => 4,
			'width'                      => 816,
			'height'                     => 352,
			'bitrate'                    => 630,
			'frameRate'                  => 24,
			'isOriginal'                 => false,
			'isWeb'                      => true,
			'containerFormat'            => 'flash video',
			'videoCodecId'               => 'vp6',
			'status'                     => 2,
			'id'                         => '0_2wlv13zq',
			'entryId'                    => '0_c0r624gh',
			'partnerId'                  => 243342,
			'version'                    => '1',
			'size'                       => 68300,
			'tags'                       => 'web,mbr',
			'fileExt'                    => 'flv',
			'createdAt'                  => 1338328264,
			'updatedAt'                  => 1338330729,
			'deletedAt'                  => NULL,
			'description'                => '',
			'URL'						=> 'http://mcott2_tvinci2-s.akamaihd.net/ondemand/201401B/FR_HD_ELLA_THE_ELEPHANT_EP2_PC_SS.ism/Manifest',
			'partnerData'                => '{"type":"flv","url": "http://cdnapi.kaltura.com/p/243342/sp/24334200/playManifest/entryId/0_swup5zao/flavorId/0_2wlv13zq/format/url/protocol/http/a.flv"}',
			'partnerDescription'         => NULL,
			'actualSourceAssetParamsIds' => NULL,
		),
		array(
			'flavorParamsId'             => 230931,
			'width'                      => 816,
			'height'                     => 352,
			'bitrate'                    => 797,
			'frameRate'                  => 24,
			'isOriginal'                 => false,
			'isWeb'                      => false,
			'containerFormat'            => 'matroska',
			'videoCodecId'               => 'v_vp8',
			'status'                     => 2,
			'id'                         => '0_1c89hhxb',
			'entryId'                    => '0_c0r624gh',
			'partnerId'                  => 243342,
			'version'                    => '1',
			'size'                       => 98816,
			'tags'                       => 'html5',
			'fileExt'                    => 'webm',
			'createdAt'                  => 1314819002,
			'updatedAt'                  => 1314821461,
			'deletedAt'                  => NULL,
			'description'                => '',
			'URL'						=> 'http://mcott2_tvinci2-s.akamaihd.net/ondemand/201401B/FR_HD_ELLA_THE_ELEPHANT_EP2_PC_SS.ism/Manifest',
			'partnerData'                => '{"type":"webm","url": "http://cdnapi.kaltura.com/p/243342/sp/24334200/playManifest/entryId/0_swup5zao/flavorId/0_1c89hhxb/format/url/protocol/http/a.webm"}',
			'partnerDescription'         => NULL,
			'actualSourceAssetParamsIds' => NULL,
		),
		array(
			'flavorParamsId'             => 62581,
			'width'                      => 480,
			'height'                     => 192,
			'bitrate'                    => 797,
			'frameRate'                  => 24,
			'isOriginal'                 => false,
			'isWeb'                      => false,
			'containerFormat'            => '3gp4',
			'videoCodecId'               => 'mpeg-4 visual',
			'status'                     => 2,
			'id'                         => '1_wvny3hay',
			'entryId'                    => '0_c0r624gh',
			'partnerId'                  => 243342,
			'version'                    => '1',
			'size'                       => 107520,
			'tags'                       => 'mpeg4,iphone,mobile',
			'fileExt'                    => '3gp',
			'createdAt'                  => 1325735067,
			'updatedAt'                  => 1325735578,
			'deletedAt'                  => NULL,
			'description'                => '',
			'URL'						=> 'http://mcott2_tvinci2-s.akamaihd.net/ondemand/201401B/FR_HD_ELLA_THE_ELEPHANT_EP2_PC_SS.ism/Manifest',
			'partnerData'                => '{"type":"3gp","url": "http://cdnapi.kaltura.com/p/243342/sp/24334200/playManifest/entryId/0_swup5zao/flavorId/1_wvny3hay/format/url/protocol/http/a.3gp"}',
			'partnerDescription'         => NULL,
			'actualSourceAssetParamsIds' => NULL,
		),
		array(
			'flavorParamsId'             => 360461,
			'width'                      => 480,
			'height'                     => 192,
			'bitrate'                    => 800,
			'frameRate'                  => 24,
			'isOriginal'                 => false,
			'isWeb'                      => true,
			'containerFormat'            => 'isom',
			'videoCodecId'               => 'avc1',
			'status'                     => 2,
			'id'                         => '1_ssz1g2sa',
			'entryId'                    => '0_c0r624gh',
			'partnerId'                  => 243342,
			'version'                    => '1',
			'size'                       => 93696,
			'tags'                       => 'iphone,h264,web,iphonenew,mobile',
			'fileExt'                    => 'mp4',
			'createdAt'                  => 1325735077,
			'updatedAt'                  => 1325735577,
			'deletedAt'                  => NULL,
			'description'                => '',
			'URL'						=> 'http://mcott2_tvinci2-s.akamaihd.net/ondemand/201401B/FR_HD_ELLA_THE_ELEPHANT_EP2_PC_SS.ism/Manifest',
			'partnerData'                => '{"type":"mp4","url": "http://cdnapi.kaltura.com/p/243342/sp/24334200/playManifest/entryId/0_swup5zao/flavorId/1_ssz1g2sa/format/url/protocol/http/a.mp4"}',
			'partnerDescription'         => NULL,
			'actualSourceAssetParamsIds' => NULL,
		),
		array(
			'flavorParamsId'             => 7,
			'width'                      => 1120,
			'height'                     => 480,
			'bitrate'                    => 1065,
			'frameRate'                  => 24,
			'isOriginal'                 => false,
			'isWeb'                      => true,
			'containerFormat'            => 'flash video',
			'videoCodecId'               => 'vp6',
			'status'                     => 2,
			'id'                         => '0_446cpweu',
			'entryId'                    => '0_c0r624gh',
			'partnerId'                  => 243342,
			'version'                    => '1',
			'size'                       => 115712,
			'tags'                       => 'edit,web',
			'fileExt'                    => 'flv',
			'createdAt'                  => 1338328268,
			'updatedAt'                  => 1338332278,
			'deletedAt'                  => NULL,
			'description'                => '',
			'URL'						=> 'http://mcott2_tvinci2-s.akamaihd.net/ondemand/201401B/FR_HD_ELLA_THE_ELEPHANT_EP2_PC_SS.ism/Manifest',
			'partnerData'                => '{"type":"flv","url": "http://cdnapi.kaltura.com/p/243342/sp/24334200/playManifest/entryId/0_swup5zao/flavorId/0_446cpweu/format/url/protocol/http/a.flv"}',
			'partnerDescription'         => NULL,
			'actualSourceAssetParamsIds' => NULL,
		),
		array(
			'flavorParamsId'             => 3,
			'width'                      => 1280,
			'height'                     => 544,
			'bitrate'                    => 1210,
			'frameRate'                  => 24,
			'isOriginal'                 => false,
			'isWeb'                      => true,
			'containerFormat'            => 'flash video',
			'videoCodecId'               => 'vp6',
			'status'                     => 2,
			'id'                         => '0_7brftsuz',
			'entryId'                    => '0_c0r624gh',
			'partnerId'                  => 243342,
			'version'                    => '1',
			'size'                       => 131072,
			'tags'                       => 'web,mbr',
			'fileExt'                    => 'flv',
			'createdAt'                  => 1338328260,
			'updatedAt'                  => 1338330231,
			'deletedAt'                  => NULL,
			'description'                => '',
			'URL'						=> 'http://mcott2_tvinci2-s.akamaihd.net/ondemand/201401B/FR_HD_ELLA_THE_ELEPHANT_EP2_PC_SS.ism/Manifest',
			'partnerData'                => '{"type":"flv","url": "http://cdnapi.kaltura.com/p/243342/sp/24334200/playManifest/entryId/0_swup5zao/flavorId/0_7brftsuz/format/url/protocol/http/a.flv"}',
			'partnerDescription'         => NULL,
			'actualSourceAssetParamsIds' => NULL,
		),
		array(
			'flavorParamsId'             => 48572,
			'width'                      => 640,
			'height'                     => 272,
			'bitrate'                    => 1211,
			'frameRate'                  => 24,
			'isOriginal'                 => false,
			'isWeb'                      => true,
			'containerFormat'            => 'isom',
			'videoCodecId'               => 'avc1',
			'status'                     => 2,
			'id'                         => '0_w3aolq8p',
			'entryId'                    => '0_c0r624gh',
			'partnerId'                  => 243342,
			'version'                    => '1',
			'size'                       => 140288,
			'tags'                       => 'iphone,h264,web,iphonenew,mobile',
			'fileExt'                    => 'mp4',
			'createdAt'                  => 1314819002,
			'updatedAt'                  => 1314819572,
			'deletedAt'                  => NULL,
			'description'                => '',
			'URL'						=> 'http://mcott2_tvinci2-s.akamaihd.net/ondemand/201401B/FR_HD_ELLA_THE_ELEPHANT_EP2_PC_SS.ism/Manifest',
			'partnerData'                => '{"type":"mp4","url": "http://cdnapi.kaltura.com/p/243342/sp/24334200/playManifest/entryId/0_swup5zao/flavorId/0_w3aolq8p/format/url/protocol/http/a.mp4"}',
			'partnerDescription'         => NULL,
			'actualSourceAssetParamsIds' => NULL,
		),
		array(
			'flavorParamsId'             => 48582,
			'width'                      => 1120,
			'height'                     => 480,
			'bitrate'                    => 1211,
			'frameRate'                  => 24,
			'isOriginal'                 => false,
			'isWeb'                      => false,
			'containerFormat'            => 'ogg',
			'videoCodecId'               => 'theora',
			'status'                     => 2,
			'id'                         => '0_g4hvuve3',
			'entryId'                    => '0_c0r624gh',
			'partnerId'                  => 243342,
			'version'                    => '1',
			'size'                       => 148480,
			'tags'                       => 'ogg,html5',
			'fileExt'                    => 'ogg',
			'createdAt'                  => 1314819002,
			'updatedAt'                  => 1314820468,
			'deletedAt'                  => NULL,
			'description'                => 'video warnings: 2106,#Redundant bitrate.audio warnings: 2106,#Redundant bitrate.',
			'URL'						=> 'http://mcott2_tvinci2-s.akamaihd.net/ondemand/201401B/FR_HD_ELLA_THE_ELEPHANT_EP2_PC_SS.ism/Manifest',
			'partnerData'                => '{"type":"ogg","url": "http://cdnapi.kaltura.com/p/243342/sp/24334200/playManifest/entryId/0_swup5zao/flavorId/0_g4hvuve3/format/url/protocol/http/a.ogg"}',
			'partnerDescription'         => NULL,
			'actualSourceAssetParamsIds' => NULL,
		),
		array(
			'flavorParamsId'             => 360471,
			'width'                      => 1024,
			'height'                     => 432,
			'bitrate'                    => 1430,
			'frameRate'                  => 24,
			'isOriginal'                 => false,
			'isWeb'                      => true,
			'containerFormat'            => 'isom',
			'videoCodecId'               => 'avc1',
			'status'                     => 2,
			'id'                         => '1_tj3uq03m',
			'entryId'                    => '0_c0r624gh',
			'partnerId'                  => 243342,
			'version'                    => '1',
			'size'                       => 173056,
			'tags'                       => 'ipad,ipadnew,web',
			'fileExt'                    => 'mp4',
			'createdAt'                  => 1325735061,
			'updatedAt'                  => 1325737235,
			'deletedAt'                  => NULL,
			'description'                => '',
			'URL'						=> 'http://mcott2_tvinci2-s.akamaihd.net/ondemand/201401B/FR_HD_ELLA_THE_ELEPHANT_EP2_PC_SS.ism/Manifest',
			'partnerData'                => '{"type":"mp4","url": "http://cdnapi.kaltura.com/p/243342/sp/24334200/playManifest/entryId/0_swup5zao/flavorId/1_tj3uq03m/format/url/protocol/http/a.mp4"}',
			'partnerDescription'         => NULL,
			'actualSourceAssetParamsIds' => NULL,
		),
		array(
			'flavorParamsId'             => 48592,
			'width'                      => 1280,
			'height'                     => 544,
			'bitrate'                    => 1919,
			'frameRate'                  => 24,
			'isOriginal'                 => false,
			'isWeb'                      => true,
			'containerFormat'            => 'isom',
			'videoCodecId'               => 'avc1',
			'status'                     => 2,
			'id'                         => '0_w48dtkyq',
			'entryId'                    => '0_c0r624gh',
			'partnerId'                  => 243342,
			'version'                    => '1',
			'size'                       => 226304,
			'tags'                       => 'ipad,ipadnew,web',
			'fileExt'                    => 'mp4',
			'createdAt'                  => 1314819002,
			'updatedAt'                  => 1314819872,
			'deletedAt'                  => NULL,
			'description'                => 'video warnings: 2106,#Redundant bitrate.',
			'URL'						=> 'http://mcott2_tvinci2-s.akamaihd.net/ondemand/201401B/FR_HD_ELLA_THE_ELEPHANT_EP2_PC_SS.ism/Manifest',
			'partnerData'                => '{"type":"mp4","url": "http://cdnapi.kaltura.com/p/243342/sp/24334200/playManifest/entryId/0_swup5zao/flavorId/0_w48dtkyq/format/url/protocol/http/a.mp4"}',
			'partnerDescription'         => NULL,
			'actualSourceAssetParamsIds' => NULL,
		),
		array(
			'flavorParamsId'             => 6,
			'width'                      => 1280,
			'height'                     => 544,
			'bitrate'                    => 2494,
			'frameRate'                  => 24,
			'isOriginal'                 => false,
			'isWeb'                      => true,
			'containerFormat'            => 'isom',
			'videoCodecId'               => 'avc1',
			'status'                     => 2,
			'id'                         => '0_mx66fwtv',
			'entryId'                    => '0_c0r624gh',
			'partnerId'                  => 243342,
			'version'                    => '1',
			'size'                       => 284672,
			'tags'                       => 'web,mp4_export',
			'fileExt'                    => 'mp4',
			'createdAt'                  => 1314819002,
			'updatedAt'                  => 1314820625,
			'deletedAt'                  => NULL,
			'description'                => 'video warnings: 2106,#Redundant bitrate.',
			'URL'						=> 'http://mcott2_tvinci2-s.akamaihd.net/ondemand/201401B/FR_HD_ELLA_THE_ELEPHANT_EP2_PC_SS.ism/Manifest',
			'partnerData'                => '{"type":"mp4","url": "http://cdnapi.kaltura.com/p/243342/sp/24334200/playManifest/entryId/0_swup5zao/flavorId/0_mx66fwtv/format/url/protocol/http/a.mp4"}',
			'partnerDescription'         => NULL,
			'actualSourceAssetParamsIds' => NULL,
		),
		array(
			'flavorParamsId'             => 2,
			'width'                      => 1280,
			'height'                     => 544,
			'bitrate'                    => 2626,
			'frameRate'                  => 24,
			'isOriginal'                 => false,
			'isWeb'                      => true,
			'containerFormat'            => 'flash video',
			'videoCodecId'               => 'h.263',
			'status'                     => 2,
			'id'                         => '0_714nzxxj',
			'entryId'                    => '0_c0r624gh',
			'partnerId'                  => 243342,
			'version'                    => '1',
			'size'                       => 284672,
			'tags'                       => 'web,mbr',
			'fileExt'                    => 'flv',
			'createdAt'                  => 1338328255,
			'updatedAt'                  => 1338328873,
			'deletedAt'                  => NULL,
			'description'                => '',
			'URL'						=> 'http://mcott2_tvinci2-s.akamaihd.net/ondemand/201401B/FR_HD_ELLA_THE_ELEPHANT_EP2_PC_SS.ism/Manifest',
			'partnerData'                => '{"type":"flv","url": "http://cdnapi.kaltura.com/p/243342/sp/24334200/playManifest/entryId/0_swup5zao/flavorId/0_714nzxxj/format/url/protocol/http/a.flv"}',
			'partnerDescription'         => NULL,
			'actualSourceAssetParamsIds' => NULL,
		),
		array(
			'flavorParamsId'             => 1,
			'width'                      => 1280,
			'height'                     => 544,
			'bitrate'                    => 3407,
			'frameRate'                  => 24,
			'isOriginal'                 => false,
			'isWeb'                      => true,
			'containerFormat'            => 'flash video',
			'videoCodecId'               => 'vp6',
			'status'                     => 2,
			'id'                         => '0_xiqnsgnn',
			'entryId'                    => '0_c0r624gh',
			'partnerId'                  => 243342,
			'version'                    => '1',
			'size'                       => 386048,
			'tags'                       => 'web,mbr',
			'fileExt'                    => 'flv',
			'createdAt'                  => 1314819002,
			'updatedAt'                  => 1314820569,
			'deletedAt'                  => NULL,
			'description'                => '',
			'URL'						=> 'http://mcott2_tvinci2-s.akamaihd.net/ondemand/201401B/FR_HD_ELLA_THE_ELEPHANT_EP2_PC_SS.ism/Manifest',
			'partnerData'                => '{"type":"flv","url": "http://cdnapi.kaltura.com/p/243342/sp/24334200/playManifest/entryId/0_swup5zao/flavorId/0_xiqnsgnn/format/url/protocol/http/a.flv"}',
			'partnerDescription'         => NULL,
			'actualSourceAssetParamsIds' => NULL,
		),
		array(
			'flavorParamsId'             => 0,
			'width'                      => 1280,
			'height'                     => 544,
			'bitrate'                    => 5310,
			'frameRate'                  => 24,
			'isOriginal'                 => true,
			'isWeb'                      => false,
			'containerFormat'            => 'matroska',
			'videoCodecId'               => 'v_mpeg4/iso/avc',
			'status'                     => 2,
			'id'                         => '0_2mn33cly',
			'entryId'                    => '0_c0r624gh',
			'partnerId'                  => 243342,
			'version'                    => '1',
			'size'                       => 658432,
			'tags'                       => '',
			'fileExt'                    => 'avi',
			'createdAt'                  => 1314818953,
			'updatedAt'                  => 1314819001,
			'deletedAt'                  => NULL,
			'description'                => '',
			'URL'						=> 'http://mcott2_tvinci2-s.akamaihd.net/ondemand/201401B/FR_HD_ELLA_THE_ELEPHANT_EP2_PC_SS.ism/Manifest',
			'partnerData'                => '{"type":"avi","url": "http://cdnapi.kaltura.com/p/243342/sp/24334200/playManifest/entryId/0_swup5zao/flavorId/0_2mn33cly/format/url/protocol/http/a.avi"}',
			'partnerDescription'         => NULL,
			'actualSourceAssetParamsIds' => NULL,
		)					
	);
	private $cuepointsData = array(
		array
		(
			"parentId"            => "0",
			"text"                => "",
			"endTime"             => "0",
			"duration"            => "0",
			"depth"               => "0",
			"childrenCount"       => "1",
			"directChildrenCount" => "1",
			"id"                  => "0_01kq6yd5",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1391649909",
			"updatedAt"           => "1391649911",
			"tags"                => "",
			"startTime"           => "0",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "0",
			"text"                => "",
			"endTime"             => "0",
			"duration"            => "0",
			"depth"               => "0",
			"childrenCount"       => "2",
			"directChildrenCount" => "2",
			"id"                  => "0_33ly17r8",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1392634796",
			"updatedAt"           => "1392634797",
			"tags"                => "",
			"startTime"           => "0",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "0",
			"text"                => "",
			"endTime"             => "0",
			"duration"            => "0",
			"depth"               => "0",
			"childrenCount"       => "1",
			"directChildrenCount" => "1",
			"id"                  => "0_3gakebqt",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1366271014",
			"updatedAt"           => "1366271015",
			"tags"                => "",
			"startTime"           => "0",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "0_k9sig38y",
			"text"                => "allow",
			"endTime"             => "0",
			"duration"            => "0",
			"depth"               => "1",
			"childrenCount"       => "0",
			"directChildrenCount" => "0",
			"id"                  => "0_8d683gl9",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1381917175",
			"updatedAt"           => "1381917175",
			"tags"                => "",
			"startTime"           => "0",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "0",
			"text"                => "",
			"endTime"             => "0",
			"duration"            => "0",
			"depth"               => "0",
			"childrenCount"       => "2",
			"directChildrenCount" => "2",
			"id"                  => "0_9jnzggw0",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1360122902",
			"updatedAt"           => "1360122902",
			"tags"                => "",
			"startTime"           => "0",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "0_3gakebqt",
			"text"                => "gfhgfhjgfghghhg",
			"endTime"             => "0",
			"duration"            => "0",
			"depth"               => "1",
			"childrenCount"       => "0",
			"directChildrenCount" => "0",
			"id"                  => "0_hob36cyz",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1366271015",
			"updatedAt"           => "1366271015",
			"tags"                => "",
			"startTime"           => "0",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "0_r3sojicr",
			"text"                => "hi",
			"endTime"             => "0",
			"duration"            => "0",
			"depth"               => "1",
			"childrenCount"       => "0",
			"directChildrenCount" => "0",
			"id"                  => "0_ij5d7udo",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1360754154",
			"updatedAt"           => "1360754154",
			"tags"                => "",
			"startTime"           => "0",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "0",
			"text"                => "",
			"endTime"             => "0",
			"duration"            => "0",
			"depth"               => "0",
			"childrenCount"       => "2",
			"directChildrenCount" => "2",
			"id"                  => "0_j4av1bz3",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1367877405",
			"updatedAt"           => "1367877406",
			"tags"                => "",
			"startTime"           => "0",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "0",
			"text"                => "",
			"endTime"             => "0",
			"duration"            => "0",
			"depth"               => "0",
			"childrenCount"       => "1",
			"directChildrenCount" => "1",
			"id"                  => "0_k9sig38y",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1381917175",
			"updatedAt"           => "1381917175",
			"tags"                => "",
			"startTime"           => "0",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "0",
			"text"                => "",
			"endTime"             => "0",
			"duration"            => "0",
			"depth"               => "0",
			"childrenCount"       => "1",
			"directChildrenCount" => "1",
			"id"                  => "0_r3sojicr",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1360754153",
			"updatedAt"           => "1360754154",
			"tags"                => "",
			"startTime"           => "0",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "0",
			"text"                => "",
			"endTime"             => "0",
			"duration"            => "0",
			"depth"               => "0",
			"childrenCount"       => "4",
			"directChildrenCount" => "4",
			"id"                  => "0_rhgeyzs8",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1403158692",
			"updatedAt"           => "1403158693",
			"tags"                => "",
			"startTime"           => "0",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "0",
			"text"                => "",
			"endTime"             => "0",
			"duration"            => "0",
			"depth"               => "0",
			"childrenCount"       => "3",
			"directChildrenCount" => "3",
			"id"                  => "0_s7z3avk4",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1392636226",
			"updatedAt"           => "1392636227",
			"tags"                => "",
			"startTime"           => "0",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "0",
			"text"                => "",
			"endTime"             => "0",
			"duration"            => "0",
			"depth"               => "0",
			"childrenCount"       => "1",
			"directChildrenCount" => "1",
			"id"                  => "0_u96557oy",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1399711180",
			"updatedAt"           => "1399711181",
			"tags"                => "",
			"startTime"           => "0",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "0",
			"text"                => "",
			"endTime"             => "0",
			"duration"            => "0",
			"depth"               => "0",
			"childrenCount"       => "1",
			"directChildrenCount" => "1",
			"id"                  => "0_y9yem4nn",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1364359575",
			"updatedAt"           => "1364359576",
			"tags"                => "",
			"startTime"           => "0",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "0",
			"text"                => "",
			"endTime"             => "0",
			"duration"            => "0",
			"depth"               => "0",
			"childrenCount"       => "1",
			"directChildrenCount" => "1",
			"id"                  => "1_c0avxv71",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1394883859",
			"updatedAt"           => "1394883860",
			"tags"                => "",
			"startTime"           => "0",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "1_fkxm2rlt",
			"text"                => "test",
			"endTime"             => "0",
			"duration"            => "0",
			"depth"               => "1",
			"childrenCount"       => "0",
			"directChildrenCount" => "0",
			"id"                  => "1_dafmg2x8",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1393360987",
			"updatedAt"           => "1393360987",
			"tags"                => "",
			"startTime"           => "0",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "0",
			"text"                => "",
			"endTime"             => "0",
			"duration"            => "0",
			"depth"               => "0",
			"childrenCount"       => "1",
			"directChildrenCount" => "1",
			"id"                  => "1_ewr4k24i",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1358924828",
			"updatedAt"           => "1358924828",
			"tags"                => "",
			"startTime"           => "0",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "0",
			"text"                => "",
			"endTime"             => "0",
			"duration"            => "0",
			"depth"               => "0",
			"childrenCount"       => "2",
			"directChildrenCount" => "2",
			"id"                  => "1_f5rrm2gt",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1401002889",
			"updatedAt"           => "1401002891",
			"tags"                => "",
			"startTime"           => "0",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "0",
			"text"                => "",
			"endTime"             => "0",
			"duration"            => "0",
			"depth"               => "0",
			"childrenCount"       => "2",
			"directChildrenCount" => "2",
			"id"                  => "1_fkxm2rlt",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1393360986",
			"updatedAt"           => "1393360988",
			"tags"                => "",
			"startTime"           => "0",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "0",
			"text"                => "",
			"endTime"             => "0",
			"duration"            => "0",
			"depth"               => "0",
			"childrenCount"       => "2",
			"directChildrenCount" => "2",
			"id"                  => "1_jfhzbhi1",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1357490943",
			"updatedAt"           => "1357490943",
			"tags"                => "",
			"startTime"           => "0",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "0",
			"text"                => "",
			"endTime"             => "0",
			"duration"            => "0",
			"depth"               => "0",
			"childrenCount"       => "1",
			"directChildrenCount" => "1",
			"id"                  => "1_kg01afv8",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1401369741",
			"updatedAt"           => "1401369742",
			"tags"                => "",
			"startTime"           => "0",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "0",
			"text"                => "",
			"endTime"             => "0",
			"duration"            => "0",
			"depth"               => "0",
			"childrenCount"       => "1",
			"directChildrenCount" => "1",
			"id"                  => "1_kwv4qj8e",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1400749174",
			"updatedAt"           => "1400749175",
			"tags"                => "",
			"startTime"           => "0",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "1_q6txo0n5",
			"text"                => "test",
			"endTime"             => "0",
			"duration"            => "0",
			"depth"               => "1",
			"childrenCount"       => "0",
			"directChildrenCount" => "0",
			"id"                  => "1_mg4k5uyi",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1403277570",
			"updatedAt"           => "1403277570",
			"tags"                => "",
			"startTime"           => "0",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "0",
			"text"                => "",
			"endTime"             => "0",
			"duration"            => "0",
			"depth"               => "0",
			"childrenCount"       => "1",
			"directChildrenCount" => "1",
			"id"                  => "1_o8yd8325",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1395916739",
			"updatedAt"           => "1395916740",
			"tags"                => "",
			"startTime"           => "0",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "0",
			"text"                => "",
			"endTime"             => "0",
			"duration"            => "0",
			"depth"               => "0",
			"childrenCount"       => "3",
			"directChildrenCount" => "3",
			"id"                  => "1_q6txo0n5",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1403277570",
			"updatedAt"           => "1403277571",
			"tags"                => "",
			"startTime"           => "0",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "0",
			"text"                => "",
			"endTime"             => "0",
			"duration"            => "0",
			"depth"               => "0",
			"childrenCount"       => "3",
			"directChildrenCount" => "3",
			"id"                  => "1_t9i0t30q",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1361050611",
			"updatedAt"           => "1361050612",
			"tags"                => "",
			"startTime"           => "0",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "0",
			"text"                => "",
			"endTime"             => "0",
			"duration"            => "0",
			"depth"               => "0",
			"childrenCount"       => "1",
			"directChildrenCount" => "1",
			"id"                  => "1_uk7y8zya",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1357489278",
			"updatedAt"           => "1357489278",
			"tags"                => "",
			"startTime"           => "0",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "0",
			"text"                => "",
			"endTime"             => "0",
			"duration"            => "0",
			"depth"               => "0",
			"childrenCount"       => "4",
			"directChildrenCount" => "4",
			"id"                  => "1_w72j01ex",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1357489819",
			"updatedAt"           => "1357489859",
			"tags"                => "",
			"startTime"           => "0",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "0",
			"text"                => "",
			"endTime"             => "0",
			"duration"            => "0",
			"depth"               => "0",
			"childrenCount"       => "1",
			"directChildrenCount" => "1",
			"id"                  => "1_wpn4zumh",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1397629690",
			"updatedAt"           => "1397629691",
			"tags"                => "",
			"startTime"           => "0",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "0",
			"text"                => "",
			"endTime"             => "0",
			"duration"            => "0",
			"depth"               => "0",
			"childrenCount"       => "2",
			"directChildrenCount" => "2",
			"id"                  => "1_wpqf4376",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1387490038",
			"updatedAt"           => "1387490058",
			"tags"                => "",
			"startTime"           => "0",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "0_u96557oy",
			"text"                => ".,.,.,.,",
			"endTime"             => "3",
			"duration"            => "0",
			"depth"               => "1",
			"childrenCount"       => "0",
			"directChildrenCount" => "0",
			"id"                  => "0_s3ctvrs7",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1399711181",
			"updatedAt"           => "1399711181",
			"tags"                => "",
			"startTime"           => "3",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "1_wpqf4376",
			"text"                => "amro",
			"endTime"             => "4",
			"duration"            => "0",
			"depth"               => "1",
			"childrenCount"       => "0",
			"directChildrenCount" => "0",
			"id"                  => "1_77ugsvlk",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1387490039",
			"updatedAt"           => "1387490039",
			"tags"                => "",
			"startTime"           => "4",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "1_t9i0t30q",
			"text"                => "Testowanie dziwne jest",
			"endTime"             => "5",
			"duration"            => "0",
			"depth"               => "1",
			"childrenCount"       => "0",
			"directChildrenCount" => "0",
			"id"                  => "1_07gbf3al",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1361050611",
			"updatedAt"           => "1361050611",
			"tags"                => "",
			"startTime"           => "5",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "1_jfhzbhi1",
			"text"                => "My first note",
			"endTime"             => "5",
			"duration"            => "0",
			"depth"               => "1",
			"childrenCount"       => "0",
			"directChildrenCount" => "0",
			"id"                  => "1_rlo8nfpv",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1357490943",
			"updatedAt"           => "1357490943",
			"tags"                => "",
			"startTime"           => "5",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "0_j4av1bz3",
			"text"                => "Test",
			"endTime"             => "7",
			"duration"            => "0",
			"depth"               => "1",
			"childrenCount"       => "0",
			"directChildrenCount" => "0",
			"id"                  => "0_oc69rwbp",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1367877406",
			"updatedAt"           => "1367877406",
			"tags"                => "",
			"startTime"           => "7",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "0_rhgeyzs8",
			"text"                => "ssdsd",
			"endTime"             => "7",
			"duration"            => "0",
			"depth"               => "1",
			"childrenCount"       => "0",
			"directChildrenCount" => "0",
			"id"                  => "0_pd17tsxs",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1403158692",
			"updatedAt"           => "1403158692",
			"tags"                => "",
			"startTime"           => "7",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "1_o8yd8325",
			"text"                => "hello",
			"endTime"             => "7",
			"duration"            => "0",
			"depth"               => "1",
			"childrenCount"       => "0",
			"directChildrenCount" => "0",
			"id"                  => "1_st5i753l",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1395916740",
			"updatedAt"           => "1395916740",
			"tags"                => "",
			"startTime"           => "7",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "1_uk7y8zya",
			"text"                => "My first note",
			"endTime"             => "8",
			"duration"            => "0",
			"depth"               => "1",
			"childrenCount"       => "0",
			"directChildrenCount" => "0",
			"id"                  => "1_33zyu2gh",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1357489278",
			"updatedAt"           => "1357489278",
			"tags"                => "",
			"startTime"           => "8",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "1_kg01afv8",
			"text"                => "okokok",
			"endTime"             => "8",
			"duration"            => "0",
			"depth"               => "1",
			"childrenCount"       => "0",
			"directChildrenCount" => "0",
			"id"                  => "1_3n2gxcnp",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1401369742",
			"updatedAt"           => "1401369742",
			"tags"                => "",
			"startTime"           => "8",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "0_33ly17r8",
			"text"                => "ttttttttttttttttttt",
			"endTime"             => "9",
			"duration"            => "0",
			"depth"               => "1",
			"childrenCount"       => "0",
			"directChildrenCount" => "0",
			"id"                  => "0_vuxnuvuc",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1392634797",
			"updatedAt"           => "1392634797",
			"tags"                => "",
			"startTime"           => "9",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "0_9jnzggw0",
			"text"                => "ㅅㄷㄴ",
			"endTime"             => "10",
			"duration"            => "0",
			"depth"               => "1",
			"childrenCount"       => "0",
			"directChildrenCount" => "0",
			"id"                  => "0_92bghbit",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1360122902",
			"updatedAt"           => "1360122902",
			"tags"                => "",
			"startTime"           => "10",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "0_y9yem4nn",
			"text"                => "This is my annotation. ",
			"endTime"             => "10",
			"duration"            => "0",
			"depth"               => "1",
			"childrenCount"       => "0",
			"directChildrenCount" => "0",
			"id"                  => "0_vzagu2fa",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1364359576",
			"updatedAt"           => "1364359576",
			"tags"                => "",
			"startTime"           => "10",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "1_w72j01ex",
			"text"                => "My Note is HERE",
			"endTime"             => "11",
			"duration"            => "0",
			"depth"               => "1",
			"childrenCount"       => "0",
			"directChildrenCount" => "0",
			"id"                  => "1_0932djog",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1357489820",
			"updatedAt"           => "1357489820",
			"tags"                => "",
			"startTime"           => "11",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "1_t9i0t30q",
			"text"                => "Nie wiem dlaczego tak działa",
			"endTime"             => "11",
			"duration"            => "0",
			"depth"               => "1",
			"childrenCount"       => "0",
			"directChildrenCount" => "0",
			"id"                  => "1_63lwcmc6",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1361050611",
			"updatedAt"           => "1361050611",
			"tags"                => "",
			"startTime"           => "11",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "1_fkxm2rlt",
			"text"                => "abc",
			"endTime"             => "11",
			"duration"            => "0",
			"depth"               => "1",
			"childrenCount"       => "0",
			"directChildrenCount" => "0",
			"id"                  => "1_mgronxte",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1393360988",
			"updatedAt"           => "1393360988",
			"tags"                => "",
			"startTime"           => "11",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "1_w72j01ex",
			"text"                => "My first note",
			"endTime"             => "12",
			"duration"            => "0",
			"depth"               => "1",
			"childrenCount"       => "0",
			"directChildrenCount" => "0",
			"id"                  => "1_il71fg1z",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1357489859",
			"updatedAt"           => "1357489859",
			"tags"                => "",
			"startTime"           => "12",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "1_kwv4qj8e",
			"text"                => "afvdbsgn",
			"endTime"             => "14",
			"duration"            => "0",
			"depth"               => "1",
			"childrenCount"       => "0",
			"directChildrenCount" => "0",
			"id"                  => "1_huaqkrgz",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1400749175",
			"updatedAt"           => "1400749175",
			"tags"                => "",
			"startTime"           => "14",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "1_f5rrm2gt",
			"text"                => "ddddd",
			"endTime"             => "16",
			"duration"            => "0",
			"depth"               => "1",
			"childrenCount"       => "0",
			"directChildrenCount" => "0",
			"id"                  => "1_tbtap24r",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1401002890",
			"updatedAt"           => "1401002890",
			"tags"                => "",
			"startTime"           => "16",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "0_s7z3avk4",
			"text"                => "vgdfkbdk'fb'd;fkbdfkbvd;skfb;sfk's;l",
			"endTime"             => "17",
			"duration"            => "0",
			"depth"               => "1",
			"childrenCount"       => "0",
			"directChildrenCount" => "0",
			"id"                  => "0_v1l4mn8c",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1392636227",
			"updatedAt"           => "1392636227",
			"tags"                => "",
			"startTime"           => "17",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "0_9jnzggw0",
			"text"                => "ㄹㄹㄹㄹㄹ",
			"endTime"             => "18",
			"duration"            => "0",
			"depth"               => "1",
			"childrenCount"       => "0",
			"directChildrenCount" => "0",
			"id"                  => "0_al17bhxc",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1360122902",
			"updatedAt"           => "1360122902",
			"tags"                => "",
			"startTime"           => "18",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "1_wpqf4376",
			"text"                => "qsdfqsdfqsdfqsdf",
			"endTime"             => "22",
			"duration"            => "0",
			"depth"               => "1",
			"childrenCount"       => "0",
			"directChildrenCount" => "0",
			"id"                  => "1_p9inphou",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1387490058",
			"updatedAt"           => "1387490058",
			"tags"                => "",
			"startTime"           => "22",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "1_t9i0t30q",
			"text"                => "Ale film jest fajny",
			"endTime"             => "23",
			"duration"            => "0",
			"depth"               => "1",
			"childrenCount"       => "0",
			"directChildrenCount" => "0",
			"id"                  => "1_xi38842z",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1361050611",
			"updatedAt"           => "1361050611",
			"tags"                => "",
			"startTime"           => "23",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "0_01kq6yd5",
			"text"                => "asdadsad sadsadasdsad sadsadsadsadasda sdasdasd ",
			"endTime"             => "32",
			"duration"            => "0",
			"depth"               => "1",
			"childrenCount"       => "0",
			"directChildrenCount" => "0",
			"id"                  => "0_m0xth8hp",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1391649911",
			"updatedAt"           => "1391649911",
			"tags"                => "",
			"startTime"           => "32",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "0_s7z3avk4",
			"text"                => "sdcxb vcb dgh nhgdghngh",
			"endTime"             => "44",
			"duration"            => "0",
			"depth"               => "1",
			"childrenCount"       => "0",
			"directChildrenCount" => "0",
			"id"                  => "0_wiq5mjzj",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1392636227",
			"updatedAt"           => "1392636227",
			"tags"                => "",
			"startTime"           => "44",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "1_c0avxv71",
			"text"                => "Choose one",
			"endTime"             => "46",
			"duration"            => "0",
			"depth"               => "1",
			"childrenCount"       => "0",
			"directChildrenCount" => "0",
			"id"                  => "1_dwznetus",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1394883860",
			"updatedAt"           => "1394883860",
			"tags"                => "",
			"startTime"           => "46",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "1_wpn4zumh",
			"text"                => "dat is hier niet juist ja dadde",
			"endTime"             => "47",
			"duration"            => "0",
			"depth"               => "1",
			"childrenCount"       => "0",
			"directChildrenCount" => "0",
			"id"                  => "1_28wfbdh2",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1397629691",
			"updatedAt"           => "1397629691",
			"tags"                => "",
			"startTime"           => "47",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "0_33ly17r8",
			"text"                => "dfgv;fksbmsfdmv;kamvdfkmvdkvdafk",
			"endTime"             => "75",
			"duration"            => "0",
			"depth"               => "1",
			"childrenCount"       => "0",
			"directChildrenCount" => "0",
			"id"                  => "0_3ygyc1zw",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1392634797",
			"updatedAt"           => "1392634797",
			"tags"                => "",
			"startTime"           => "75",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "0_s7z3avk4",
			"text"                => "wepdf,dbkoavo",
			"endTime"             => "76",
			"duration"            => "0",
			"depth"               => "1",
			"childrenCount"       => "0",
			"directChildrenCount" => "0",
			"id"                  => "0_n0g5a5nm",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1392636227",
			"updatedAt"           => "1392636227",
			"tags"                => "",
			"startTime"           => "76",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "0_rhgeyzs8",
			"text"                => "sdsdddd",
			"endTime"             => "80",
			"duration"            => "0",
			"depth"               => "1",
			"childrenCount"       => "0",
			"directChildrenCount" => "0",
			"id"                  => "0_hma70mso",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1403158692",
			"updatedAt"           => "1403158692",
			"tags"                => "",
			"startTime"           => "80",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "0_rhgeyzs8",
			"text"                => "sdsddd",
			"endTime"             => "106",
			"duration"            => "0",
			"depth"               => "1",
			"childrenCount"       => "0",
			"directChildrenCount" => "0",
			"id"                  => "0_jftlthf5",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1403158693",
			"updatedAt"           => "1403158693",
			"tags"                => "",
			"startTime"           => "106",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "1_ewr4k24i",
			"text"                => "ddddd",
			"endTime"             => "141",
			"duration"            => "0",
			"depth"               => "1",
			"childrenCount"       => "0",
			"directChildrenCount" => "0",
			"id"                  => "1_rp3bvrg3",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1358924828",
			"updatedAt"           => "1358924828",
			"tags"                => "",
			"startTime"           => "141",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "1_w72j01ex",
			"text"                => "My second note",
			"endTime"             => "231",
			"duration"            => "0",
			"depth"               => "1",
			"childrenCount"       => "0",
			"directChildrenCount" => "0",
			"id"                  => "1_sh2p6h6n",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1357489820",
			"updatedAt"           => "1357489820",
			"tags"                => "",
			"startTime"           => "231",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "1_f5rrm2gt",
			"text"                => "yyyy",
			"endTime"             => "262",
			"duration"            => "0",
			"depth"               => "1",
			"childrenCount"       => "0",
			"directChildrenCount" => "0",
			"id"                  => "1_8a53ehw5",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1401002891",
			"updatedAt"           => "1401002891",
			"tags"                => "",
			"startTime"           => "262",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "0_j4av1bz3",
			"text"                => "test2",
			"endTime"             => "278",
			"duration"            => "0",
			"depth"               => "1",
			"childrenCount"       => "0",
			"directChildrenCount" => "0",
			"id"                  => "0_hnkols8n",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1367877406",
			"updatedAt"           => "1367877406",
			"tags"                => "",
			"startTime"           => "278",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "1_q6txo0n5",
			"text"                => "test2",
			"endTime"             => "285",
			"duration"            => "0",
			"depth"               => "1",
			"childrenCount"       => "0",
			"directChildrenCount" => "0",
			"id"                  => "1_hmzwgq58",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1403277571",
			"updatedAt"           => "1403277571",
			"tags"                => "",
			"startTime"           => "285",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "0_rhgeyzs8",
			"text"                => "sdsdsd",
			"endTime"             => "296",
			"duration"            => "0",
			"depth"               => "1",
			"childrenCount"       => "0",
			"directChildrenCount" => "0",
			"id"                  => "0_0ley1cho",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1403158693",
			"updatedAt"           => "1403158693",
			"tags"                => "",
			"startTime"           => "296",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "1_jfhzbhi1",
			"text"                => "M second note",
			"endTime"             => "369",
			"duration"            => "0",
			"depth"               => "1",
			"childrenCount"       => "0",
			"directChildrenCount" => "0",
			"id"                  => "1_d1c4n52a",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1357490943",
			"updatedAt"           => "1357490943",
			"tags"                => "",
			"startTime"           => "369",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "1_w72j01ex",
			"text"                => "My final comment is HERE",
			"endTime"             => "428",
			"duration"            => "0",
			"depth"               => "1",
			"childrenCount"       => "0",
			"directChildrenCount" => "0",
			"id"                  => "1_l279vxko",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1357489820",
			"updatedAt"           => "1357489820",
			"tags"                => "",
			"startTime"           => "428",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"parentId"            => "1_q6txo0n5",
			"text"                => "test 3",
			"endTime"             => "464",
			"duration"            => "0",
			"depth"               => "1",
			"childrenCount"       => "0",
			"directChildrenCount" => "0",
			"id"                  => "1_9h82e7yf",
			"cuePointType"        => "annotation.Annotation",
			"status"              => "1",
			"entryId"             => "0_c0r624gh",
			"partnerId"           => "243342",
			"createdAt"           => "1403277571",
			"updatedAt"           => "1403277571",
			"tags"                => "",
			"startTime"           => "464",
			"userId"              => "0",
			"partnerData"         => "",
			"partnerSortValue"    => "",
			"forceStop"           => "",
			"thumbOffset"         => "",
			"systemName"          => "",
		),
		array
		(
			"protocolType"     => "1",
			"sourceUrl"        => "http://projects.kaltura.com/mdale/hotelVastAd.xml",
			"adType"           => "1",
			"title"            => "Vast Ad 10 Seconds",
			"endTime"          => "9473",
			"duration"         => "0",
			"id"               => "1_wrmilfjt",
			"cuePointType"     => "adCuePoint.Ad",
			"status"           => "1",
			"entryId"          => "0_c0r624gh",
			"partnerId"        => "243342",
			"createdAt"        => "1386371074",
			"updatedAt"        => "1386613166",
			"tags"             => "",
			"startTime"        => "9473",
			"userId"           => "__ADMIN__242942",
			"partnerData"      => "",
			"partnerSortValue" => "",
			"forceStop"        => "",
			"thumbOffset"      => "",
			"systemName"       => "",
		)
	);
	function getData($key) {
		
		switch($key){
			case "baseentry":
				$data = $this->baseentryData;
				break;
			case "metadata":
				$data = $this->metadataData;
				break;
			case "session":
				$data = $this->sessionData;
				break;
			case "entrycontextdata":
				$data = $this->entrycontextdataData;
				break;
			case "flavorassets":
				$data = $this->flavorassetsData;
				break;
			case "cuepoints":
				$data = $this->cuepointsData;
				break;
			default:
				$data = array();
		}
		return $data;
	}

	function setData($key, $data) {
		
		switch($key){
			case "baseentry":
				$this->baseentryData = $data;
				break;
			case "metadata":
				$this->metadataData = $data;
				break;
			case "session":
				$this->sessionData = $data;
				break;
			case "entrycontextdata":
				$this->entrycontextdataData = $data;
				break;
			case "flavorassets":
				$this->flavorassetsData = $data;
				break;
			case "cuepoints":
				$this->cuepointsData = $data;
				break;
			case "all":
				$this->baseentryData = $data;
				$this->metadataData = $data;
				$this->sessionData = $data;
				$this->entrycontextdataData = $data;
				$this->flavorassetsData = $data;
				$this->cuepointsData = $data;
				break;
			default:				
		}
		
	}

}
?>